"""counterparties

Revision ID: 3192bf92e184
Revises: 6965daac15a9
Create Date: 2026-09-29 16:17:57.655707

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3192bf92e184'
down_revision: Union[str, Sequence[str], None] = '6965daac15a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('counterparties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('counterparty_type', sa.String(length=20), nullable=False),
    sa.Column('relation', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("counterparty_type IN ('PERSON', 'BUSINESS', 'ORGANIZATION')", name='ck_counterparties_type_valid'),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_counterparties_owner_user_id'), 'counterparties', ['owner_user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_counterparties_owner_user_id'), table_name='counterparties')
    op.drop_table('counterparties')
    # ### end Alembic commands ###
