"""items discounts payment methods

Revision ID: 472557987d4b
Revises: ae4880f45b58
Create Date: 2026-09-29 17:01:33.515179

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '472557987d4b'
down_revision: Union[str, Sequence[str], None] = 'ae4880f45b58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('expense_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('expense_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=10, scale=3), server_default='1', nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.CheckConstraint('amount > 0', name='ck_expense_items_amount_positive'),
    sa.CheckConstraint('quantity > 0', name='ck_expense_items_quantity_positive'),
    sa.ForeignKeyConstraint(['expense_id'], ['expenses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_expense_items_expense_id'), 'expense_items', ['expense_id'], unique=False)
    op.add_column('expense_payments', sa.Column('method', sa.String(length=30), nullable=True))
    op.add_column('expense_payments', sa.Column('provider', sa.String(length=100), nullable=True))
    op.add_column('expenses', sa.Column('discount_amount', sa.Numeric(precision=12, scale=2), server_default='0', nullable=False))
    op.add_column('expenses', sa.Column('original_amount', sa.Numeric(precision=12, scale=2), sa.Computed('amount + discount_amount', persisted=True), nullable=False))

    # Autogenerate doesn't detect CHECKs added to existing tables. The
    # method list is typed out: a migration is a snapshot and must not
    # import values that can change later.
    op.create_check_constraint(
        "ck_expenses_discount_non_negative",
        "expenses",
        "discount_amount >= 0",
    )
    op.create_check_constraint(
        "ck_expense_payments_method_valid",
        "expense_payments",
        "method IS NULL OR method IN ('cash', 'upi', 'credit_card', "
        "'debit_card', 'card', 'bank_transfer', 'wallet', 'other')",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("ck_expense_payments_method_valid", "expense_payments", type_="check")
    op.drop_constraint("ck_expenses_discount_non_negative", "expenses", type_="check")
    op.drop_column('expenses', 'original_amount')
    op.drop_column('expenses', 'discount_amount')
    op.drop_column('expense_payments', 'provider')
    op.drop_column('expense_payments', 'method')
    op.drop_index(op.f('ix_expense_items_expense_id'), table_name='expense_items')
    op.drop_table('expense_items')
    # ### end Alembic commands ###
