"""payments and participants

Revision ID: 511cce97d84e
Revises: 3192bf92e184
Create Date: 2026-09-29 16:42:36.434426

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '511cce97d84e'
down_revision: Union[str, Sequence[str], None] = '3192bf92e184'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('expense_participants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('expense_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('counterparty_id', sa.Integer(), nullable=True),
    sa.Column('share_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.CheckConstraint('(user_id IS NULL) <> (counterparty_id IS NULL)', name='ck_expense_participants_one_person'),
    sa.CheckConstraint('share_amount > 0', name='ck_expense_participants_share_positive'),
    sa.ForeignKeyConstraint(['counterparty_id'], ['counterparties.id'], ),
    sa.ForeignKeyConstraint(['expense_id'], ['expenses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('expense_id', 'counterparty_id', name='uq_expense_participants_counterparty'),
    sa.UniqueConstraint('expense_id', 'user_id', name='uq_expense_participants_user')
    )
    op.create_index(op.f('ix_expense_participants_counterparty_id'), 'expense_participants', ['counterparty_id'], unique=False)
    op.create_index(op.f('ix_expense_participants_expense_id'), 'expense_participants', ['expense_id'], unique=False)
    op.create_table('expense_payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('expense_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('counterparty_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.CheckConstraint('(user_id IS NULL) <> (counterparty_id IS NULL)', name='ck_expense_payments_one_payer'),
    sa.CheckConstraint('amount > 0', name='ck_expense_payments_amount_positive'),
    sa.ForeignKeyConstraint(['counterparty_id'], ['counterparties.id'], ),
    sa.ForeignKeyConstraint(['expense_id'], ['expenses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_expense_payments_counterparty_id'), 'expense_payments', ['counterparty_id'], unique=False)
    op.create_index(op.f('ix_expense_payments_expense_id'), 'expense_payments', ['expense_id'], unique=False)
    op.add_column('expenses', sa.Column('counterparty_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_expenses_counterparty_id'), 'expenses', ['counterparty_id'], unique=False)
    op.create_foreign_key('fk_expenses_counterparty_id_counterparties', 'expenses', 'counterparties', ['counterparty_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_expenses_counterparty_id_counterparties', 'expenses', type_='foreignkey')
    op.drop_index(op.f('ix_expenses_counterparty_id'), table_name='expenses')
    op.drop_column('expenses', 'counterparty_id')
    op.drop_index(op.f('ix_expense_payments_expense_id'), table_name='expense_payments')
    op.drop_index(op.f('ix_expense_payments_counterparty_id'), table_name='expense_payments')
    op.drop_table('expense_payments')
    op.drop_index(op.f('ix_expense_participants_expense_id'), table_name='expense_participants')
    op.drop_index(op.f('ix_expense_participants_counterparty_id'), table_name='expense_participants')
    op.drop_table('expense_participants')
    # ### end Alembic commands ###
