"""expense charges

Revision ID: 5d87ffdbfe13
Revises: 472557987d4b
Create Date: 2026-09-30 00:48:47.948156

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d87ffdbfe13'
down_revision: Union[str, Sequence[str], None] = '472557987d4b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('expense_charges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('expense_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.CheckConstraint("kind IN ('tax', 'service_charge', 'delivery', 'packaging', 'tip', 'fee', 'rounding', 'other')", name='ck_expense_charges_kind_valid'),
    sa.CheckConstraint('amount > 0', name='ck_expense_charges_amount_positive'),
    sa.ForeignKeyConstraint(['expense_id'], ['expenses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_expense_charges_expense_id'), 'expense_charges', ['expense_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_expense_charges_expense_id'), table_name='expense_charges')
    op.drop_table('expense_charges')
    # ### end Alembic commands ###
