"""expense category

Revision ID: 6965daac15a9
Revises: 0faa71108fe3
Create Date: 2026-09-29 15:46:38.500318

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6965daac15a9'
down_revision: Union[str, Sequence[str], None] = '0faa71108fe3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expenses', sa.Column('category', sa.String(length=30), server_default='other', nullable=False))
    op.create_index(op.f('ix_expenses_category'), 'expenses', ['category'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_expenses_category'), table_name='expenses')
    op.drop_column('expenses', 'category')
    # ### end Alembic commands ###
