"""settlements

Revision ID: ae4880f45b58
Revises: 1b7285b0323f
Create Date: 2026-09-29 16:56:58.120375

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae4880f45b58'
down_revision: Union[str, Sequence[str], None] = '1b7285b0323f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('settlements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('counterparty_id', sa.Integer(), nullable=False),
    sa.Column('direction', sa.String(length=20), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("direction IN ('they_paid_me', 'i_paid_them')", name='ck_settlements_direction_valid'),
    sa.CheckConstraint('amount > 0', name='ck_settlements_amount_positive'),
    sa.ForeignKeyConstraint(['counterparty_id'], ['counterparties.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_settlements_counterparty_id'), 'settlements', ['counterparty_id'], unique=False)
    op.create_index(op.f('ix_settlements_user_id'), 'settlements', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_settlements_user_id'), table_name='settlements')
    op.drop_index(op.f('ix_settlements_counterparty_id'), table_name='settlements')
    op.drop_table('settlements')
    # ### end Alembic commands ###
